<?php

/**
 * EvidenceScorer - evidence assembly + composite scoring orchestrator
 * for AtoM Heratio
 *
 * Task 4 of the AHG Authority Resolution Engine. Given a mention with
 * candidates already generated by CandidateGeneratorService (Task 3),
 * this service:
 *
 *   1. Loads the mention + its derived context (Task 2 output).
 *   2. For each candidate row, runs every evaluator whose
 *      supports($entity_type) returns true.
 *   3. Collects per-dimension signals into evidence_signals JSON.
 *   4. Collects per-dimension data payloads into evidence_data JSON.
 *   5. Computes composite score:
 *
 *        composite = name_similarity_score
 *        for each dimension signal:
 *           match    => composite += 0.10
 *           conflict => composite -= 0.30
 *           silent   => composite += 0.00
 *           absent   => composite += 0.00
 *        composite = clamp(composite, 0.0, 1.0)
 *
 *   6. UPDATEs ahg_mention_candidate with signals + data + composite
 *      + computed_at.
 *   7. After all candidates for a mention are scored, re-ranks them
 *      by composite_score DESC inside a single transaction so the
 *      rank_position column stays coherent with composite_score.
 *
 * Identical formula and evaluator wiring to the Laravel-side
 * Heratio\Packages\AhgAuthorityResolution\Services\EvidenceScorer so
 * the same candidate set re-ranks identically on either platform.
 *
 * Copyright (C) 2026 Johan Pieterse
 * Plain Sailing Information Systems
 * Email: johan@plainsailingisystems.co.za
 *
 * This file is part of the AHG Authority Resolution Engine plugin for
 * AtoM Heratio. Licensed under the GNU General Public License v3.0 or later,
 * matching the parent atom-ahg-plugins repository.
 */

namespace AtomFramework\Services\AuthorityResolution;

use AtomFramework\Services\AuthorityResolution\Evidence\DocumentPriorService;
use AtomFramework\Services\AuthorityResolution\Evidence\EvaluatorInterface;
use AtomFramework\Services\AuthorityResolution\Evidence\EvidenceSignal;
use Illuminate\Database\Capsule\Manager as DB;

class EvidenceScorer
{
    /** @var EvaluatorInterface[] */
    private $evaluators;

    /** @var DocumentPriorService */
    private $prior;

    /**
     * @param EvaluatorInterface[] $evaluators
     */
    public function __construct(array $evaluators, DocumentPriorService $prior)
    {
        $this->evaluators = $evaluators;
        $this->prior = $prior; // held for symmetry with Laravel-side constructor;
        // PriorEvaluator already has its own reference.
    }

    /**
     * Score every candidate row attached to $mentionId and re-rank them
     * by the new composite_score. Returns the number of candidates
     * scored.
     */
    public function scoreAllForMention(int $mentionId): int
    {
        $candidates = DB::table('ahg_mention_candidate')
            ->where('mention_id', $mentionId)
            ->orderBy('rank_position')
            ->get();

        if (count($candidates) === 0) {
            return 0;
        }

        foreach ($candidates as $candidate) {
            $this->scoreCandidate((int) $candidate->id);
        }
        $this->rerankCandidates($mentionId);
        return count($candidates);
    }

    /**
     * Score a single candidate row. Returns the result payload
     * {signals, data, composite_score} for inspection by callers.
     */
    public function scoreCandidate(int $candidateId): array
    {
        $candidate = DB::table('ahg_mention_candidate')->where('id', $candidateId)->first();
        if (!$candidate) {
            return [
                'signals' => [],
                'data' => [],
                'composite_score' => null,
                'error' => 'candidate_not_found',
            ];
        }

        $mention = DB::table('ahg_mention as m')
            ->join('ahg_ner_entity as n', 'n.id', '=', 'm.ner_entity_id')
            ->where('m.id', $candidate->mention_id)
            ->first(['m.id', 'm.object_id', 'm.entity_type', 'n.entity_value']);
        if (!$mention) {
            return [
                'signals' => [],
                'data' => [],
                'composite_score' => null,
                'error' => 'mention_not_found',
            ];
        }

        $context = DB::table('ahg_mention_context')->where('mention_id', $mention->id)->first();
        if (!$context) {
            $context = (object) [
                'nearby_dates' => null,
                'nearby_places' => null,
                'co_occurring_entities' => null,
                'role_language_tokens' => null,
            ];
        }

        $signals = [];
        $data = [];
        foreach ($this->evaluators as $evaluator) {
            if (!$evaluator->supports((string) $mention->entity_type)) {
                continue;
            }
            $dim = $evaluator->dimension();
            try {
                $result = $evaluator->evaluate($mention, $context, $candidate);
            } catch (\Throwable $e) {
                $signals[$dim] = EvidenceSignal::ABSENT;
                $data[$dim] = ['error' => $e->getMessage()];
                continue;
            }
            $signals[$dim] = $result['signal'] ?? EvidenceSignal::ABSENT;
            $data[$dim] = $result['data'] ?? [];
        }

        $composite = (float) $candidate->name_similarity_score;
        foreach ($signals as $sig) {
            $composite += EvidenceSignal::delta($sig);
        }
        $composite = max(0.0, min(1.0, $composite));
        $composite = round($composite, 4);

        DB::table('ahg_mention_candidate')
            ->where('id', $candidateId)
            ->update([
                'evidence_signals' => json_encode($signals, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'evidence_data' => json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'composite_score' => $composite,
                'computed_at' => date('Y-m-d H:i:s'),
            ]);

        return [
            'signals' => $signals,
            'data' => $data,
            'composite_score' => $composite,
        ];
    }

    /**
     * Re-rank candidates for a mention by composite_score DESC, with
     * candidate_display_name ASC as deterministic tie-breaker.
     */
    private function rerankCandidates(int $mentionId): void
    {
        DB::transaction(function () use ($mentionId) {
            $rows = DB::table('ahg_mention_candidate')
                ->where('mention_id', $mentionId)
                ->orderByRaw('composite_score DESC, candidate_display_name ASC, id ASC')
                ->get(['id']);
            $rank = 1;
            foreach ($rows as $row) {
                DB::table('ahg_mention_candidate')
                    ->where('id', $row->id)
                    ->update(['rank_position' => $rank]);
                $rank++;
            }
        });
    }
}
