<?php slot('title') ?><?php echo __('Donor Agreements') ?><?php end_slot() ?>
<?php slot('before-content') ?>
<div class="browse-filters mb-4"><form method="get" action="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'browse']) ?>"><div class="row g-3">
<div class="col-md-4"><div class="input-group"><input type="text" name="sq" class="form-control" placeholder="<?php echo __('Search...') ?>" value="<?php echo esc_entities($sf_request->getParameter('sq')) ?>"><button type="submit" class="btn btn-secondary"><i class="fas fa-search"></i></button></div></div>
<div class="col-md-2"><select name="status" class="form-select"><option value=""><?php echo __('All statuses') ?></option><?php foreach ($statuses as $v => $l): ?><option value="<?php echo $v ?>" <?php echo $sf_request->getParameter('status') == $v ? 'selected' : '' ?>><?php echo __($l) ?></option><?php endforeach ?></select></div>
<div class="col-md-2"><select name="type" class="form-select"><option value=""><?php echo __('All types') ?></option><?php foreach ($agreementTypes as $t): ?><option value="<?php echo $t->id ?>" <?php echo $sf_request->getParameter('type') == $t->id ? 'selected' : '' ?>><?php echo esc_entities($t->name) ?></option><?php endforeach ?></select></div>
<div class="col-md-2"><button type="submit" class="btn btn-primary w-100"><?php echo __('Filter') ?></button></div>
<div class="col-md-2"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'add']) ?>" class="btn btn-success w-100"><i class="fas fa-plus me-1"></i><?php echo __('Add') ?></a></div>
</div></form></div>
<?php end_slot() ?>
<div class="table-responsive"><table class="table table-striped table-hover"><thead><tr><th><?php echo __('Agreement #') ?></th><th><?php echo __('Title') ?></th><th><?php echo __('Type') ?></th><th><?php echo __('Donor') ?></th><th><?php echo __('Status') ?></th><th><?php echo __('Date') ?></th><th><?php echo __('Expiry') ?></th><th class="text-end"><?php echo __('Actions') ?></th></tr></thead><tbody>
<?php foreach ($agreements as $a): ?><tr><td><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'view', 'id' => $a->id]) ?>"><?php echo esc_entities($a->agreement_number) ?></a></td><td><?php echo esc_entities($a->title) ?></td><td><?php echo esc_entities($a->agreement_type_name) ?></td><td><?php echo esc_entities($a->donor_name ?: $a->institution_name) ?></td><td><span class="badge bg-<?php echo match($a->status) { 'active' => 'success', 'draft' => 'secondary', 'pending_review', 'pending_signature' => 'warning', 'expired' => 'danger', default => 'info' } ?>"><?php echo __(ucwords(str_replace('_', ' ', $a->status))) ?></span></td><td><?php echo $a->agreement_date ? format_date($a->agreement_date, 'd') : '-' ?></td><td><?php echo $a->expiry_date ? format_date($a->expiry_date, 'd') : __('Perpetual') ?></td><td class="text-end"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'view', 'id' => $a->id]) ?>" class="btn btn-sm btn-outline-secondary"><i class="fas fa-eye"></i></a> <a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'edit', 'id' => $a->id]) ?>" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i></a></td></tr><?php endforeach ?>
<?php if (empty($agreements)): ?><tr><td colspan="8" class="text-center text-muted py-4"><?php echo __('No agreements found.') ?></td></tr><?php endif ?>
</tbody></table></div>
