<?php use_helper('Date'); ?>
<?php slot('title') ?><?php echo __('Agreement Dashboard') ?><?php end_slot() ?>
<div class="row mb-4">
<div class="col-md-3 mb-3"><div class="card bg-primary text-white h-100"><div class="card-body"><h6 class="text-white-50"><?php echo __('Total') ?></h6><h2 class="mb-0"><?php echo number_format($dashboardData['statistics']['total'] ?? 0) ?></h2></div></div></div>
<div class="col-md-3 mb-3"><div class="card bg-success text-white h-100"><div class="card-body"><h6 class="text-white-50"><?php echo __('Active') ?></h6><h2 class="mb-0"><?php echo number_format($dashboardData['statistics']['active'] ?? 0) ?></h2></div></div></div>
<div class="col-md-3 mb-3"><div class="card bg-warning text-dark h-100"><div class="card-body"><h6><?php echo __('Expiring Soon') ?></h6><h2 class="mb-0"><?php echo number_format($dashboardData['statistics']['expiring_soon'] ?? 0) ?></h2></div></div></div>
<div class="col-md-3 mb-3"><div class="card bg-info text-white h-100"><div class="card-body"><h6 class="text-white-50"><?php echo __('Review Due') ?></h6><h2 class="mb-0"><?php echo number_format($dashboardData['statistics']['review_due'] ?? 0) ?></h2></div></div></div>
</div>
<div class="row">
<div class="col-lg-6 mb-4"><div class="card h-100"><div class="card-header"><h5 class="mb-0"><i class="fas fa-bell text-warning me-2"></i><?php echo __('Pending Reminders') ?></h5></div><div class="card-body p-0"><?php if (!empty($dashboardData['pending_reminders'])): ?><div class="list-group list-group-flush"><?php foreach ($dashboardData['pending_reminders'] as $r): ?><div class="list-group-item"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'view', 'id' => $r->donor_agreement_id]) ?>"><strong><?php echo esc_entities($r->title) ?></strong></a><br><small class="text-muted"><?php echo esc_entities($r->agreement_number) ?> - <?php echo format_date($r->reminder_date, 'd') ?></small></div><?php endforeach ?></div><?php else: ?><div class="text-center text-muted py-4"><?php echo __('No pending reminders') ?></div><?php endif ?></div></div></div>
<div class="col-lg-6 mb-4"><div class="card h-100"><div class="card-header"><h5 class="mb-0"><i class="fas fa-hourglass-half text-danger me-2"></i><?php echo __('Expiring Soon') ?></h5></div><div class="card-body p-0"><?php if (!empty($dashboardData['expiring_soon'])): ?><table class="table table-sm mb-0"><tbody><?php foreach ($dashboardData['expiring_soon'] as $a): ?><tr><td><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'view', 'id' => $a->id]) ?>"><?php echo esc_entities($a->agreement_number) ?></a></td><td><?php echo esc_entities($a->donor_name) ?></td><td class="text-end text-danger"><?php echo format_date($a->expiry_date, 'd') ?></td></tr><?php endforeach ?></tbody></table><?php else: ?><div class="text-center text-muted py-4"><?php echo __('No agreements expiring soon') ?></div><?php endif ?></div></div></div>
</div>
<div class="card"><div class="card-header"><h5 class="mb-0"><i class="fas fa-bolt me-2"></i><?php echo __('Quick Actions') ?></h5></div><div class="card-body"><div class="row g-3">
<div class="col-md-3"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'add']) ?>" class="btn btn-success w-100"><i class="fas fa-plus me-2"></i><?php echo __('New Agreement') ?></a></div>
<div class="col-md-3"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'browse']) ?>" class="btn btn-primary w-100"><i class="fas fa-list me-2"></i><?php echo __('Browse All') ?></a></div>
<div class="col-md-3"><a href="<?php echo url_for(['module' => 'donorAgreement', 'action' => 'browse', 'status' => 'draft']) ?>" class="btn btn-secondary w-100"><i class="fas fa-edit me-2"></i><?php echo __('Drafts') ?></a></div>
<div class="col-md-3"><a href="<?php echo url_for(['module' => 'donor', 'action' => 'browse']) ?>" class="btn btn-info w-100"><i class="fas fa-users me-2"></i><?php echo __('Donors') ?></a></div>
</div></div></div>
