<?php slot('title') ?><?php echo isset($agreement) ? __('Edit Agreement') : __('Add Agreement') ?><?php end_slot() ?>
<form method="post" action="">
<section class="card mb-4"><div class="card-header"><h2 class="h5 mb-0"><i class="fas fa-file-contract me-2"></i><?php echo __('Agreement Details') ?></h2></div><div class="card-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label"><?php echo __('Agreement Type') ?> *</label><select name="agreement[agreement_type_id]" class="form-select" required><option value=""><?php echo __('Select...') ?></option><?php foreach ($agreementTypes as $t): ?><option value="<?php echo $t->id ?>" <?php echo ($form->getDefault('agreement_type_id') == $t->id) ? 'selected' : '' ?>><?php echo esc_entities($t->name) ?></option><?php endforeach ?></select></div>
<div class="col-md-6"><label class="form-label"><?php echo __('Status') ?></label><select name="agreement[status]" class="form-select"><option value="draft" <?php echo ($form->getDefault('status') == 'draft') ? 'selected' : '' ?>><?php echo __('Draft') ?></option><option value="pending_review" <?php echo ($form->getDefault('status') == 'pending_review') ? 'selected' : '' ?>><?php echo __('Pending Review') ?></option><option value="pending_signature" <?php echo ($form->getDefault('status') == 'pending_signature') ? 'selected' : '' ?>><?php echo __('Pending Signature') ?></option><option value="active" <?php echo ($form->getDefault('status') == 'active') ? 'selected' : '' ?>><?php echo __('Active') ?></option></select></div>
<div class="col-12"><label class="form-label"><?php echo __('Title') ?> *</label><input type="text" name="agreement[title]" class="form-control" required value="<?php echo esc_entities($form->getDefault('title')) ?>"></div>
<div class="col-12"><label class="form-label"><?php echo __('Description') ?></label><textarea name="agreement[description]" class="form-control" rows="3"><?php echo esc_entities($form->getDefault('description')) ?></textarea></div>
<div class="col-md-3"><label class="form-label"><?php echo __('Agreement Date') ?></label><input type="date" name="agreement[agreement_date]" class="form-control" value="<?php echo $form->getDefault('agreement_date') ?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo __('Effective Date') ?></label><input type="date" name="agreement[effective_date]" class="form-control" value="<?php echo $form->getDefault('effective_date') ?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo __('Expiry Date') ?></label><input type="date" name="agreement[expiry_date]" class="form-control" value="<?php echo $form->getDefault('expiry_date') ?>"></div>
<div class="col-md-3"><label class="form-label"><?php echo __('Review Date') ?></label><input type="date" name="agreement[review_date]" class="form-control" value="<?php echo $form->getDefault('review_date') ?>"></div>
</div></div></section>
<section class="card mb-4"><div class="card-header"><h2 class="h5 mb-0"><i class="fas fa-users me-2"></i><?php echo __('Parties') ?></h2></div><div class="card-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label"><?php echo __('Donor Name') ?></label><input type="text" name="agreement[donor_name]" class="form-control" value="<?php echo esc_entities($form->getDefault('donor_name')) ?>"></div>
<div class="col-md-6"><label class="form-label"><?php echo __('Legal Representative') ?></label><input type="text" name="agreement[legal_representative]" class="form-control" value="<?php echo esc_entities($form->getDefault('legal_representative')) ?>"></div>
<div class="col-md-6"><label class="form-label"><?php echo __('Repository Representative') ?></label><input type="text" name="agreement[repository_representative]" class="form-control" value="<?php echo esc_entities($form->getDefault('repository_representative')) ?>"></div>
</div></div></section>
<section class="card mb-4"><div class="card-header"><h2 class="h5 mb-0"><i class="fas fa-boxes me-2"></i><?php echo __('Scope') ?></h2></div><div class="card-body"><div class="row g-3">
<div class="col-12"><label class="form-label"><?php echo __('Scope Description') ?></label><textarea name="agreement[scope_description]" class="form-control" rows="3"><?php echo esc_entities($form->getDefault('scope_description')) ?></textarea></div>
<div class="col-md-6"><label class="form-label"><?php echo __('Extent') ?></label><input type="text" name="agreement[extent_statement]" class="form-control" value="<?php echo esc_entities($form->getDefault('extent_statement')) ?>" placeholder="e.g., 50 linear meters"></div>
</div></div></section>
<section class="card mb-4"><div class="card-header"><h2 class="h5 mb-0"><i class="fas fa-gavel me-2"></i><?php echo __('Terms') ?></h2></div><div class="card-body"><div class="row g-3">
<div class="col-12"><label class="form-label"><?php echo __('General Terms') ?></label><textarea name="agreement[general_terms]" class="form-control" rows="4"><?php echo esc_entities($form->getDefault('general_terms')) ?></textarea></div>
<div class="col-12"><label class="form-label"><?php echo __('Special Conditions') ?></label><textarea name="agreement[special_conditions]" class="form-control" rows="4"><?php echo esc_entities($form->getDefault('special_conditions')) ?></textarea></div>
</div></div></section>
<?php if (!isset($agreement)): ?>
<section class="card mb-4"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0"><i class="fas fa-balance-scale me-2"></i><?php echo __('Rights') ?></h2><button type="button" class="btn btn-sm btn-outline-success" onclick="addRight()"><?php echo __('Add Right') ?></button></div><div class="card-body" id="rights-container"></div></section>
<section class="card mb-4"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0"><i class="fas fa-lock me-2"></i><?php echo __('Restrictions') ?></h2><button type="button" class="btn btn-sm btn-outline-warning" onclick="addRestriction()"><?php echo __('Add Restriction') ?></button></div><div class="card-body" id="restrictions-container"></div></section>
<?php endif ?>
<div class="d-flex justify-content-between mb-4"><a href="<?php echo isset($agreement) ? url_for(['module' => 'donorAgreement', 'action' => 'view', 'id' => $agreement['id']]) : url_for(['module' => 'donorAgreement', 'action' => 'browse']) ?>" class="btn btn-secondary"><?php echo __('Cancel') ?></a><button type="submit" class="btn btn-primary"><i class="fas fa-save me-1"></i><?php echo __('Save') ?></button></div>
</form>
<script>let rightIdx=0,restrictionIdx=0;function addRight(){const h=`<div class="border rounded p-3 mb-2 bg-light"><div class="row g-2"><div class="col-md-4"><select name="rights[${rightIdx}][right_type]" class="form-select form-select-sm"><option value="">Select...</option><option value="replicate">Replicate</option><option value="digitize">Digitize</option><option value="publish">Publish</option><option value="display">Display</option><option value="reproduce">Reproduce</option><option value="loan">Loan</option><option value="commercial_use">Commercial Use</option></select></div><div class="col-md-3"><select name="rights[${rightIdx}][permission]" class="form-select form-select-sm"><option value="granted">Granted</option><option value="conditional">Conditional</option><option value="prohibited">Prohibited</option></select></div><div class="col-md-5"><input type="text" name="rights[${rightIdx}][conditions]" class="form-control form-control-sm" placeholder="Conditions..."></div></div></div>`;document.getElementById('rights-container').insertAdjacentHTML('beforeend',h);rightIdx++}function addRestriction(){const h=`<div class="border rounded p-3 mb-2 bg-light"><div class="row g-2"><div class="col-md-4"><select name="restrictions[${restrictionIdx}][restriction_type]" class="form-select form-select-sm"><option value="">Select...</option><option value="closure">Closure</option><option value="permission_only">Permission Required</option><option value="researcher_only">Researchers Only</option><option value="onsite_only">Onsite Only</option><option value="no_copying">No Copying</option><option value="time_embargo">Time Embargo</option><option value="popia_restricted">POPIA Restricted</option></select></div><div class="col-md-3"><input type="date" name="restrictions[${restrictionIdx}][release_date]" class="form-control form-control-sm"></div><div class="col-md-4"><input type="text" name="restrictions[${restrictionIdx}][reason]" class="form-control form-control-sm" placeholder="Reason..."></div><div class="col-md-1"><div class="form-check"><input type="checkbox" name="restrictions[${restrictionIdx}][auto_release]" value="1" class="form-check-input"><label class="form-check-label small">Auto</label></div></div></div></div>`;document.getElementById('restrictions-container').insertAdjacentHTML('beforeend',h);restrictionIdx++}</script>
