<?php

namespace ahgDataMigrationPlugin\Exporters;

/**
 * Museum (Spectrum 5.0) CSV exporter for AtoM import.
 */
class MuseumExporter extends BaseExporter
{
    public function getSectorCode(): string
    {
        return 'museum';
    }

    public function getColumns(): array
    {
        return [
            'legacyId',
            'parentId',
            'objectNumber',
            'otherNumber',
            'objectName',
            'title',
            'numberOfObjects',
            'briefDescription',
            'comments',
            'distinguishingFeatures',
            'objectProductionPerson',
            'objectProductionPersonRole',
            'objectProductionOrganisation',
            'objectProductionOrganisationRole',
            'objectProductionDate',
            'objectProductionPlace',
            'objectProductionNote',
            'technique',
            'materials',
            'dimensions',
            'dimensionType',
            'dimensionValue',
            'dimensionUnit',
            'inscriptions',
            'objectHistoryNote',
            'associatedPerson',
            'associatedOrganisation',
            'associatedDate',
            'associatedPlace',
            'associatedEvent',
            'ownershipHistory',
            'acquisitionMethod',
            'acquisitionDate',
            'acquisitionSource',
            'acquisitionReason',
            'currentLocation',
            'normalLocation',
            'locationDate',
            'conditionDate',
            'condition',
            'conditionNote',
            'subjectAccessPoints',
            'placeAccessPoints',
            'nameAccessPoints',
            'digitalObjectPath',
            'digitalObjectURI',
        ];
    }

    public function mapRecord(array $record): array
    {
        $mapping = [
            'legacy_id' => 'legacyId',
            'legacyId' => 'legacyId',
            'parent_id' => 'parentId',
            'parentId' => 'parentId',
            'object_number' => 'objectNumber',
            'objectNumber' => 'objectNumber',
            'accession_number' => 'objectNumber',
            'identifier' => 'objectNumber',
            'other_number' => 'otherNumber',
            'otherNumber' => 'otherNumber',
            'object_name' => 'objectName',
            'objectName' => 'objectName',
            'title' => 'title',
            'name' => 'title',
            'number_of_objects' => 'numberOfObjects',
            'numberOfObjects' => 'numberOfObjects',
            'quantity' => 'numberOfObjects',
            'brief_description' => 'briefDescription',
            'briefDescription' => 'briefDescription',
            'description' => 'briefDescription',
            'scope_and_content' => 'briefDescription',
            'comments' => 'comments',
            'notes' => 'comments',
            'distinguishing_features' => 'distinguishingFeatures',
            'distinguishingFeatures' => 'distinguishingFeatures',
            'object_production_person' => 'objectProductionPerson',
            'objectProductionPerson' => 'objectProductionPerson',
            'maker' => 'objectProductionPerson',
            'creator' => 'objectProductionPerson',
            'artist' => 'objectProductionPerson',
            'object_production_person_role' => 'objectProductionPersonRole',
            'objectProductionPersonRole' => 'objectProductionPersonRole',
            'maker_role' => 'objectProductionPersonRole',
            'object_production_organisation' => 'objectProductionOrganisation',
            'objectProductionOrganisation' => 'objectProductionOrganisation',
            'manufacturer' => 'objectProductionOrganisation',
            'object_production_organisation_role' => 'objectProductionOrganisationRole',
            'objectProductionOrganisationRole' => 'objectProductionOrganisationRole',
            'object_production_date' => 'objectProductionDate',
            'objectProductionDate' => 'objectProductionDate',
            'date_made' => 'objectProductionDate',
            'production_date' => 'objectProductionDate',
            'date' => 'objectProductionDate',
            'object_production_place' => 'objectProductionPlace',
            'objectProductionPlace' => 'objectProductionPlace',
            'place_made' => 'objectProductionPlace',
            'production_place' => 'objectProductionPlace',
            'object_production_note' => 'objectProductionNote',
            'objectProductionNote' => 'objectProductionNote',
            'technique' => 'technique',
            'materials' => 'materials',
            'material' => 'materials',
            'medium' => 'materials',
            'dimensions' => 'dimensions',
            'measurement' => 'dimensions',
            'dimension_type' => 'dimensionType',
            'dimensionType' => 'dimensionType',
            'dimension_value' => 'dimensionValue',
            'dimensionValue' => 'dimensionValue',
            'dimension_unit' => 'dimensionUnit',
            'dimensionUnit' => 'dimensionUnit',
            'inscriptions' => 'inscriptions',
            'inscription' => 'inscriptions',
            'marks' => 'inscriptions',
            'object_history_note' => 'objectHistoryNote',
            'objectHistoryNote' => 'objectHistoryNote',
            'history' => 'objectHistoryNote',
            'provenance' => 'objectHistoryNote',
            'associated_person' => 'associatedPerson',
            'associatedPerson' => 'associatedPerson',
            'associated_organisation' => 'associatedOrganisation',
            'associatedOrganisation' => 'associatedOrganisation',
            'associated_date' => 'associatedDate',
            'associatedDate' => 'associatedDate',
            'associated_place' => 'associatedPlace',
            'associatedPlace' => 'associatedPlace',
            'associated_event' => 'associatedEvent',
            'associatedEvent' => 'associatedEvent',
            'ownership_history' => 'ownershipHistory',
            'ownershipHistory' => 'ownershipHistory',
            'acquisition_method' => 'acquisitionMethod',
            'acquisitionMethod' => 'acquisitionMethod',
            'acquisition_date' => 'acquisitionDate',
            'acquisitionDate' => 'acquisitionDate',
            'acquisition_source' => 'acquisitionSource',
            'acquisitionSource' => 'acquisitionSource',
            'donor' => 'acquisitionSource',
            'acquisition_reason' => 'acquisitionReason',
            'acquisitionReason' => 'acquisitionReason',
            'current_location' => 'currentLocation',
            'currentLocation' => 'currentLocation',
            'location' => 'currentLocation',
            'normal_location' => 'normalLocation',
            'normalLocation' => 'normalLocation',
            'location_date' => 'locationDate',
            'locationDate' => 'locationDate',
            'condition_date' => 'conditionDate',
            'conditionDate' => 'conditionDate',
            'condition' => 'condition',
            'condition_note' => 'conditionNote',
            'conditionNote' => 'conditionNote',
            'subjects' => 'subjectAccessPoints',
            'subjectAccessPoints' => 'subjectAccessPoints',
            'places' => 'placeAccessPoints',
            'placeAccessPoints' => 'placeAccessPoints',
            'names' => 'nameAccessPoints',
            'nameAccessPoints' => 'nameAccessPoints',
            'digital_object_path' => 'digitalObjectPath',
            'digitalObjectPath' => 'digitalObjectPath',
            'digital_object_uri' => 'digitalObjectURI',
            'digitalObjectURI' => 'digitalObjectURI',
            'image' => 'digitalObjectPath',
        ];

        $result = [];
        foreach ($record as $key => $value) {
            $targetKey = $mapping[$key] ?? $key;
            if (in_array($targetKey, $this->getColumns())) {
                $result[$targetKey] = $value;
            }
        }

        return $result;
    }
}
