-- ahgChatbotPlugin - Ask the Archive
-- Conversation log. No IP address is stored (POPIA); content is PII-masked
-- before insert and purged after chatbot_retention_days by chatbot:purge-logs.

CREATE TABLE IF NOT EXISTS ahg_chatbot_message (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL COMMENT 'user, assistant',
    content TEXT NOT NULL,
    sources JSON NULL,
    mode VARCHAR(16) NULL COMMENT 'ai, fallback, empty, limited',
    answered TINYINT(1) NULL COMMENT 'assistant turns: 1 = at least one record cited',
    rating TINYINT NULL COMMENT 'assistant turns: 1 = helpful, -1 = not helpful',
    model VARCHAR(100) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_chatbot_session (session_id),
    INDEX idx_chatbot_created (created_at),
    INDEX idx_chatbot_role_created (role, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Defaults. INSERT IGNORE so an administrator's values survive a reinstall.
INSERT IGNORE INTO ahg_settings (setting_key, setting_value, setting_group) VALUES
    ('chatbot_enabled', '1', 'chatbot'),
    ('chatbot_public', '1', 'chatbot'),
    ('chatbot_daily_cap', '1000', 'chatbot'),
    ('chatbot_retention_days', '30', 'chatbot'),
    ('chatbot_button_label', 'Ask the archive', 'chatbot'),
    ('chatbot_notice', 'Answers are generated by AI from this catalogue and may contain mistakes - check the linked records. Please do not enter personal information.', 'chatbot');
