-- #118 records-manage: email capture queue (capture business email as records).
CREATE TABLE IF NOT EXISTS `rm_email_capture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_id` VARCHAR(255) NOT NULL,
  `from_address` VARCHAR(500) DEFAULT NULL,
  `to_addresses` TEXT DEFAULT NULL,
  `cc_addresses` TEXT DEFAULT NULL,
  `subject` VARCHAR(1000) DEFAULT NULL,
  `sent_at` DATETIME DEFAULT NULL,
  `received_at` DATETIME DEFAULT NULL,
  `body_text` MEDIUMTEXT DEFAULT NULL,
  `body_html` MEDIUMTEXT DEFAULT NULL,
  `attachment_count` INT NOT NULL DEFAULT 0,
  `eml_storage_path` VARCHAR(1000) DEFAULT NULL,
  `capture_source` VARCHAR(20) NOT NULL DEFAULT 'eml_upload' COMMENT 'eml_upload, imap, msg_upload',
  `status` VARCHAR(16) NOT NULL DEFAULT 'captured' COMMENT 'captured, classified, declared',
  `fileplan_node_id` INT UNSIGNED DEFAULT NULL COMMENT 'rm_fileplan_node.id',
  `disposal_class_id` INT UNSIGNED DEFAULT NULL,
  `information_object_id` INT DEFAULT NULL COMMENT 'set when declared as a record',
  `captured_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_email_message_id` (`message_id`),
  KEY `idx_email_status` (`status`),
  KEY `idx_email_node` (`fileplan_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
